# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fastPdist <- function(Ar, Br) {
    .Call('_RFastDistance_fastPdist', PACKAGE = 'RFastDistance', Ar, Br)
}

