# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute the partial distance between matrices
#' 
#' This function computes the distance between a matrix of data points and a
#' matrix of reference points. Both matrices need to have the same number of
#' dimensions (columns). The code was taked from here: // C++ code taken from here:
#' https://www.r-bloggers.com/pairwise-distances-in-r/
#' 
#' @param Ar A numeric n-by-m matrix containing the position of n data points m-dimensional points
#' @param Br A numeric k-by-m matrix containing the position of k reference m-dimensional points
#' 
#' @return A numeric n-by-k matrix reporting the euclidean distance between the n data points and 
#' the k reference points
#' 
#' @export
#' 
#' @examples 
#' 
#' A <- matrix(runif(10000*100), nrow = 10000)
#' B <- matrix(runif(100*100), nrow = 100)
#' 
#' library(distutils)
#' 
#' print(system.time(C1 <- PartialDistance(A, B)))
#' print(system.time(C2 <- as.matrix(dist(rbind(A,B)))[1:10000, 10001:10100]))
#' 
#' summary(as.vector(C1 - C2))
#' 
#' 
PartialDistance <- function(Ar, Br) {
    .Call('_distutils_PartialDistance', PACKAGE = 'distutils', Ar, Br)
}

#' Parition a set of data ponints into groups based on the distance from a set of reference points
#' 
#' This function computes the distance between a matrix of data points and a
#' matrix of reference points. Then associate each point with a id inicating the closet
#' reference point
#' 
#' @param Ar A numeric n-by-m matrix containing the position of n data points m-dimensional points
#' @param Br A numeric k-by-m matrix containing the position of k reference m-dimensional points
#' @param SquaredAr A numeric vector reporting the sum, by row, of Ar (i.e. SquaredX = rowSums(Ar^2)).
#' This is done to speed up the calculation when the same set o data points is clustered against
#' a different set of reference point (e.g. in k-means)
#' 
#' @return A list with two elements:
#' * Patition is an integer vector indicating, for each point, the index of the closest reference point
#' * Distance is a numeric vector indicating, for each point, the squared distance to the closest reference point
#' @md
#' 
#' @export
#' 
#' @examples 
#' 
#' A <- matrix(runif(10000*100), nrow = 10000)
#' B <- matrix(runif(100*100), nrow = 100)
#'   
#'   library(distutils)
#'   
#'   print(
#'     system.time(
#'       Part <- Partition(Ar = A, Br = B, SquaredAr = rowSums(A^2))
#'     )
#'   )
#'   
#'   print(
#'     system.time({
#'       C2 <- as.matrix(dist(rbind(A,B)))[1:10000, 10001:10100]
#'       Partition <- apply(C2, 1, which.min)
#'       Dist <- apply(C2, 1, min)^2
#'     })
#'   )
#'   
#'   summary(Partition - Part$Patition)
#'   summary(Dist - Part$Dist)
#' 
Partition <- function(Ar, Br, SquaredAr) {
    .Call('_distutils_Partition', PACKAGE = 'distutils', Ar, Br, SquaredAr)
}

#' Compute the elastic energy associated with a particular configuration 
#' 
#' This function computes the elastic energy associate to a set of points and graph embedded
#' into them. See XXX for reference
#' 
#' @param X A numeric n-by-m matrix containing the position of n data points m-dimensional points
#' @param NodePositions A numeric k-by-m matrix containing the position of the k nodes of the embedded graph
#' @param ElasticMatrix A numeric l-by-l matrix containing the elastic parameters associates with the edge
#' of the embedded graph
#' @param Dists A numeric vector containind the squared distance of the data points to the closest node of the graph
#' 
#' @return A list with four elements:
#' * ElasticEnergy is the total energy
#' * EP is the EP component of the energy
#' * RS is the RS component of the energy
#' * MSE is the MSE component of the energy
#' @md
#' 
#' @export
#' 
#' @examples 
#' 
ElasticEnergy <- function(X, NodePositions, ElasticMatrix, Dists) {
    .Call('_distutils_ElasticEnergy', PACKAGE = 'distutils', X, NodePositions, ElasticMatrix, Dists)
}

#' Compute the elastic energy associated with a particular configuration (Old version)
#' 
#' This function computes the elastic energy associate to a set of points and graph embedded
#' into them. See XXX for reference
#' 
#' @param X A numeric n-by-m matrix containing the position of n data points m-dimensional points
#' @param NodePositions A numeric k-by-m matrix containing the position of the k nodes of the embedded graph
#' @param ElasticMatrix A numeric l-by-l matrix containing the elastic parameters associates with the edge
#' of the embedded graph
#' @param Dists A numeric vector containind the squared distance of the data points to the closest node of the graph
#' 
#' @return A list with four elements:
#' * ElasticEnergy is the total energy
#' * EP is the EP component of the energy
#' * RS is the RS component of the energy
#' * MSE is the MSE component of the energy
#' @md
#' 
#' @export
#' 
#' @examples 
#' 
ElasticEnergy_V0 <- function(X, NodePositions, ElasticMatrix, Dists) {
    .Call('_distutils_ElasticEnergy_V0', PACKAGE = 'distutils', X, NodePositions, ElasticMatrix, Dists)
}

#' Compute the penalized elastic energy associated with a particular configuration 
#' 
#' This function computes the elastic energy associate to a set of points and graph embedded
#' into them. See XXX for reference
#' 
#' @param X A numeric n-by-m matrix containing the position of n data points m-dimensional points
#' @param NodePositions A numeric k-by-m matrix containing the position of the k nodes of the embedded graph
#' @param ElasticMatrix A numeric l-by-l matrix containing the elastic parameters associates with the edge
#' of the embedded graph
#' @param Dists A numeric vector containind the squared distance of the data points to the closest node of the graph
#' @param alpha 
#' @param beta
#' 
#' @return A list with four elements:
#' * ElasticEnergy is the total energy
#' * EP is the EP component of the energy
#' * RS is the RS component of the energy
#' * MSE is the MSE component of the energy
#' @md
#' 
#' @export
#' 
#' @examples 
#' 
PenalizedElasticEnergy <- function(X, NodePositions, ElasticMatrix, Dists, alpha, beta) {
    .Call('_distutils_PenalizedElasticEnergy', PACKAGE = 'distutils', X, NodePositions, ElasticMatrix, Dists, alpha, beta)
}

ComputeWeightedAverage <- function(X, partition, PointWeights, NumberOfNodes) {
    .Call('_distutils_ComputeWeightedAverage', PACKAGE = 'distutils', X, partition, PointWeights, NumberOfNodes)
}

#' 
FitGraph2DataGivenPartition <- function(X, PointWeights, NodePositions, SpringLaplacianMatrix, partition, FastSolve) {
    .Call('_distutils_FitGraph2DataGivenPartition', PACKAGE = 'distutils', X, PointWeights, NodePositions, SpringLaplacianMatrix, partition, FastSolve)
}

#' Compute the number of points within a given distance
#' 
#' This function computes the distance between a matrix of data points and a
#' single reference points. A sorted distance vector define the reference distances
#' to consider
#' 
#' @param Ar A numeric n-by-m matrix containing the position of n data points m-dimensional points
#' @param P A m dimensional vector matrix containing the position of the reference point
#' @param DVect A k dimensional vector matrix containing the k distances to consider
#' 
#' @return A k-dimensional vector containing the number of points with a distance lower than k
#' 
#' @export
#' 
#' @examples 
#' 
#' A <- matrix(runif(10000*100), nrow = 10000)
#' B <- matrix(runif(100*100), nrow = 100)
#' 
#' library(distutils)
#' 
#' print(system.time(C1 <- PartialDistance(A, B)))
#' print(system.time(C2 <- as.matrix(dist(rbind(A,B)))[1:10000, 10001:10100]))
#' 
#' summary(as.vector(C1 - C2))
#' 
#' 
RadialCount <- function(Ar, Pr, SquaredAr, DVect) {
    .Call('_distutils_RadialCount', PACKAGE = 'distutils', Ar, Pr, SquaredAr, DVect)
}

